"""Generate and check the PantryOS release-readiness ledger."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
ACCEPTANCE_PATH = ROOT / "docs" / "handoff" / "08_ACCEPTANCE_CRITERIA.md"
STATUS_PATH = ROOT / "docs" / "handoff" / "IMPLEMENTATION_STATUS.md"
READINESS_PATH = ROOT / "docs" / "release" / "RELEASE_READINESS.md"
CRITERION_RE = re.compile(r"^- \[[ xX]\] (?P<id>[A-J][0-9]+)\. (?P<text>.+)$")
PHASE_RE = re.compile(r"^- \[(?P<done>[ xX])\] (?P<name>.+)$")
EVIDENCE_RE = re.compile(r"^\| (?P<date>20\d\d-[^|]+) \| (?P<phase>[^|]+) \| (?P<change>[^|]+) \| (?P<commands>[^|]+) \| (?P<gap>[^|]+) \|")


@dataclass(frozen=True)
class Criterion:
    id: str
    text: str


@dataclass(frozen=True)
class PhaseGate:
    name: str
    complete: bool


@dataclass(frozen=True)
class EvidenceRow:
    date: str
    phase: str
    change: str
    commands: str
    gap: str


class ReleaseReadinessError(AssertionError):
    """Raised when the generated release readiness artifact is stale."""


def parse_acceptance(text: str) -> list[Criterion]:
    criteria: list[Criterion] = []
    for line in text.splitlines():
        match = CRITERION_RE.match(line)
        if match:
            criteria.append(Criterion(match.group("id"), match.group("text")))
    return criteria


def parse_phase_gates(text: str) -> list[PhaseGate]:
    gates: list[PhaseGate] = []
    in_phase_gates = False
    for line in text.splitlines():
        if line == "## Phase gates":
            in_phase_gates = True
            continue
        if in_phase_gates and line.startswith("## "):
            break
        if in_phase_gates:
            match = PHASE_RE.match(line)
            if match:
                gates.append(PhaseGate(match.group("name"), match.group("done").lower() == "x"))
    return gates


def parse_evidence(text: str) -> list[EvidenceRow]:
    rows: list[EvidenceRow] = []
    for line in text.splitlines():
        match = EVIDENCE_RE.match(line)
        if match and match.group("phase") != "Phase":
            rows.append(
                EvidenceRow(
                    date=match.group("date").strip(),
                    phase=match.group("phase").strip(),
                    change=_strip_markdown(match.group("change")),
                    commands=match.group("commands").strip(),
                    gap=_strip_markdown(match.group("gap")),
                )
            )
    return rows


def parse_open_blockers(text: str) -> list[str]:
    marker = "## Open blockers"
    if marker not in text:
        return ["Implementation status does not contain an Open blockers section."]
    section = text.split(marker, 1)[1]
    blockers: list[str] = []
    current: list[str] = []
    for line in section.splitlines():
        if line.startswith("## "):
            break
        if line.startswith("- "):
            if current:
                blockers.append(" ".join(current).strip())
            current = [line[2:].strip()]
        elif current and line.strip():
            current.append(line.strip())
    if current:
        blockers.append(" ".join(current).strip())
    return blockers


def readiness_summary() -> dict[str, Any]:
    acceptance_text = ACCEPTANCE_PATH.read_text(encoding="utf-8")
    status_text = STATUS_PATH.read_text(encoding="utf-8")
    criteria = parse_acceptance(acceptance_text)
    gates = parse_phase_gates(status_text)
    evidence = parse_evidence(status_text)
    blockers = parse_open_blockers(status_text)
    open_gates = [gate.name for gate in gates if not gate.complete]
    ready = not open_gates and not blockers
    return {
        "generated_at": datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "decision": "PASS" if ready else "NOT READY",
        "acceptance_criteria_count": len(criteria),
        "phase_gate_count": len(gates),
        "open_phase_gates": open_gates,
        "open_blockers": blockers,
        "latest_evidence": evidence[-8:],
        "required_release_commands": release_commands(),
    }


def release_commands() -> list[str]:
    return [
        "python scripts/check.py",
        "python scripts/smoke_e2e.py",
        "python scripts/concurrency_smoke.py",
        "node scripts/browser_smoke.cjs",
        "python scripts/container_smoke.py",
        "python scripts/receipt_ocr_corpus_smoke.py",
        "python scripts/image_hardening_audit.py",
        "python scripts/supply_chain_audit.py",
        "python scripts/ha_installed_smoke.py",
        "python scripts/ha_core_live_smoke.py",
        "python scripts/release_artifact_audit.py",
        "python scripts/release_readiness.py --check",
    ]


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# PantryOS release readiness",
        "",
        "This file is generated by `python scripts/release_readiness.py --write` from the acceptance criteria and implementation status ledger.",
        "",
        "## Decision",
        "",
        f"- Status: **{summary['decision']}**",
        f"- Generated: `{summary['generated_at']}`",
        f"- Acceptance criteria in contract: `{summary['acceptance_criteria_count']}`",
        f"- Phase gates in ledger: `{summary['phase_gate_count']}`",
        "",
        "## Required Release Commands",
        "",
    ]
    for command in summary["required_release_commands"]:
        lines.append(f"- `{command}`")
    lines.extend(["", "## Open Phase Gates", ""])
    open_gates = summary["open_phase_gates"]
    if open_gates:
        for gate in open_gates:
            lines.append(f"- {gate}")
    else:
        lines.append("- None")
    lines.extend(["", "## Residual Risks", ""])
    blockers = summary["open_blockers"]
    if blockers:
        for blocker in blockers:
            lines.append(f"- {blocker}")
    else:
        lines.append("- None")
    lines.extend(["", "## Latest Evidence", ""])
    for row in summary["latest_evidence"]:
        lines.append(f"- {row.date} `{row.phase}`: {row.change}")
        lines.append(f"  Evidence: {row.commands}")
        lines.append(f"  Remaining: {row.gap}")
    lines.extend(["", "## Machine Summary", "", "```json"])
    serializable = {
        **summary,
        "latest_evidence": [row.__dict__ if isinstance(row, EvidenceRow) else row for row in summary["latest_evidence"]],
    }
    lines.append(json.dumps(serializable, indent=2, sort_keys=True))
    lines.extend(["```", ""])
    return "\n".join(lines)


def write_readiness() -> str:
    summary = readiness_summary()
    content = render_markdown(summary)
    READINESS_PATH.parent.mkdir(parents=True, exist_ok=True)
    READINESS_PATH.write_text(content, encoding="utf-8")
    return content


def check_readiness() -> None:
    expected = render_markdown(readiness_summary())
    try:
        actual = READINESS_PATH.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise ReleaseReadinessError(f"Missing release readiness file: {READINESS_PATH}") from exc
    normalized_actual = _normalize_generated_at(actual)
    normalized_expected = _normalize_generated_at(expected)
    if normalized_actual != normalized_expected:
        raise ReleaseReadinessError("Release readiness file is stale; run python scripts/release_readiness.py --write")


def _normalize_generated_at(text: str) -> str:
    text = re.sub(r"- Generated: `[^`]+`", "- Generated: `<normalized>`", text)
    return re.sub(r'"generated_at": "[^"]+"', '"generated_at": "<normalized>"', text)


def _strip_markdown(text: str) -> str:
    return text.strip().replace("`", "")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate or check PantryOS release readiness.")
    parser.add_argument("--write", action="store_true", help="Write docs/release/RELEASE_READINESS.md")
    parser.add_argument("--check", action="store_true", help="Check that docs/release/RELEASE_READINESS.md is current")
    parser.add_argument("--json", action="store_true", help="Print machine-readable summary")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.write:
        write_readiness()
        if not args.json:
            print(f"wrote {READINESS_PATH}")
    if args.check:
        check_readiness()
        if not args.json:
            print(f"release readiness current: {READINESS_PATH}")
    if args.json or not (args.write or args.check):
        summary = readiness_summary()
        printable = {
            **summary,
            "latest_evidence": [row.__dict__ if isinstance(row, EvidenceRow) else row for row in summary["latest_evidence"]],
        }
        print(json.dumps(printable, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
